run:
  tests: false
  skip-dirs:
  - "mocks"
linters-settings:
  golint: {}
  gocritic:
    enabled-checks: []
    disabled-checks:
      - regexpMust
  goheader:
    values:
      regexp:
        COMPANY: .*
    template: |-
      Copyright © {{ YEAR }} {{ COMPANY }}
      
      SPDX-License-Identifier: Apache-2.0
      
      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at
      
          http://www.apache.org/licenses/LICENSE-2.0
      
      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
linters:
  disable-all: false
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
