// Code generated by mockery v1.0.0. DO NOT EDIT.

package syscoremocks

import (
	context "context"

	fftypes "github.com/hyperledger-labs/firefly/pkg/fftypes"
	mock "github.com/stretchr/testify/mock"

	system "github.com/hyperledger-labs/firefly/internal/events/system"
)

// SystemCore is an autogenerated mock type for the SystemCore type
type SystemCore struct {
	mock.Mock
}

// AddSystemEventListener provides a mock function with given fields: ns, el
func (_m *SystemCore) AddSystemEventListener(ns string, el system.EventListener) error {
	ret := _m.Called(ns, el)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, system.EventListener) error); ok {
		r0 = rf(ns, el)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResolveSigningIdentity provides a mock function with given fields: ctx, suppliedIdentity
func (_m *SystemCore) ResolveSigningIdentity(ctx context.Context, suppliedIdentity string) (*fftypes.Identity, error) {
	ret := _m.Called(ctx, suppliedIdentity)

	var r0 *fftypes.Identity
	if rf, ok := ret.Get(0).(func(context.Context, string) *fftypes.Identity); ok {
		r0 = rf(ctx, suppliedIdentity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fftypes.Identity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, suppliedIdentity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
