// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package enginemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Engine) Close() {
	_m.Called()
}

// Init provides a mock function with given fields: ctx
func (_m *Engine) Init(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
