// Code generated by mockery v1.0.0. DO NOT EDIT.

package tokenmocks

import (
	fftypes "github.com/hyperledger-labs/firefly/pkg/fftypes"
	mock "github.com/stretchr/testify/mock"
)

// Callbacks is an autogenerated mock type for the Callbacks type
type Callbacks struct {
	mock.Mock
}

// TokenPoolCreated provides a mock function with given fields: pool, signingIdentity, additionalInfo
func (_m *Callbacks) TokenPoolCreated(pool *fftypes.TokenPool, signingIdentity string, additionalInfo fftypes.JSONObject) error {
	ret := _m.Called(pool, signingIdentity, additionalInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(*fftypes.TokenPool, string, fftypes.JSONObject) error); ok {
		r0 = rf(pool, signingIdentity, additionalInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TokensTxUpdate provides a mock function with given fields: txTrackingID, txState, errorMessage, additionalInfo
func (_m *Callbacks) TokensTxUpdate(txTrackingID string, txState fftypes.OpStatus, errorMessage string, additionalInfo fftypes.JSONObject) error {
	ret := _m.Called(txTrackingID, txState, errorMessage, additionalInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, fftypes.OpStatus, string, fftypes.JSONObject) error); ok {
		r0 = rf(txTrackingID, txState, errorMessage, additionalInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
