// Code generated by mockery v1.0.0. DO NOT EDIT.

package batchmocks

import (
	batch "github.com/hyperledger-labs/firefly/internal/batch"
	fftypes "github.com/hyperledger-labs/firefly/pkg/fftypes"

	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Manager) Close() {
	_m.Called()
}

// NewMessages provides a mock function with given fields:
func (_m *Manager) NewMessages() chan<- int64 {
	ret := _m.Called()

	var r0 chan<- int64
	if rf, ok := ret.Get(0).(func() chan<- int64); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan<- int64)
		}
	}

	return r0
}

// RegisterDispatcher provides a mock function with given fields: msgTypes, handler, batchOptions
func (_m *Manager) RegisterDispatcher(msgTypes []fftypes.LowerCasedType, handler batch.DispatchHandler, batchOptions batch.Options) {
	_m.Called(msgTypes, handler, batchOptions)
}

// Start provides a mock function with given fields:
func (_m *Manager) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WaitStop provides a mock function with given fields:
func (_m *Manager) WaitStop() {
	_m.Called()
}
