// Code generated by mockery v2.38.0. DO NOT EDIT.

package blockchainmocks

import (
	blockchain "github.com/hyperledger/firefly/pkg/blockchain"
	mock "github.com/stretchr/testify/mock"
)

// Callbacks is an autogenerated mock type for the Callbacks type
type Callbacks struct {
	mock.Mock
}

// BlockchainEventBatch provides a mock function with given fields: batch
func (_m *Callbacks) BlockchainEventBatch(batch []*blockchain.EventToDispatch) error {
	ret := _m.Called(batch)

	if len(ret) == 0 {
		panic("no return value specified for BlockchainEventBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*blockchain.EventToDispatch) error); ok {
		r0 = rf(batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCallbacks creates a new instance of Callbacks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCallbacks(t interface {
	mock.TestingT
	Cleanup(func())
}) *Callbacks {
	mock := &Callbacks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
