// Code generated by mockery v1.0.0. DO NOT EDIT.

package namespacemocks

import (
	context "context"

	config "github.com/hyperledger/firefly-common/pkg/config"

	database "github.com/hyperledger/firefly/pkg/database"

	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// GetDefaultKey provides a mock function with given fields: ns
func (_m *Manager) GetDefaultKey(ns string) string {
	ret := _m.Called(ns)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(ns)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetMultipartyConfig provides a mock function with given fields: ns, key
func (_m *Manager) GetMultipartyConfig(ns string, key config.RootKey) string {
	ret := _m.Called(ns, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, config.RootKey) string); ok {
		r0 = rf(ns, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Init provides a mock function with given fields: ctx, di
func (_m *Manager) Init(ctx context.Context, di database.Plugin) error {
	ret := _m.Called(ctx, di)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, database.Plugin) error); ok {
		r0 = rf(ctx, di)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
