// Code generated by mockery v1.0.0. DO NOT EDIT.

package namespacemocks

import (
	context "context"

	config "github.com/hyperledger/firefly-common/pkg/config"

	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// GetConfigWithFallback provides a mock function with given fields: ns, key
func (_m *Manager) GetConfigWithFallback(ns string, key config.RootKey) string {
	ret := _m.Called(ns, key)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, config.RootKey) string); ok {
		r0 = rf(ns, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Init provides a mock function with given fields: ctx
func (_m *Manager) Init(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
