// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package blockchain

import (
	fftypes "github.com/kaleido-io/firefly/internal/fftypes"
	mock "github.com/stretchr/testify/mock"
)

// MockEvents is an autogenerated mock type for the Events type
type MockEvents struct {
	mock.Mock
}

// SequencedBroadcastBatch provides a mock function with given fields: batch, pinnedSequence, additionalInfo
func (_m *MockEvents) SequencedBroadcastBatch(batch BroadcastBatch, pinnedSequence string, additionalInfo map[string]interface{}) {
	_m.Called(batch, pinnedSequence, additionalInfo)
}

// TransactionUpdate provides a mock function with given fields: txTrackingID, txState, errorMessage, additionalInfo
func (_m *MockEvents) TransactionUpdate(txTrackingID string, txState fftypes.TransactionState, errorMessage string, additionalInfo map[string]interface{}) {
	_m.Called(txTrackingID, txState, errorMessage, additionalInfo)
}
