// Code generated by mockery v1.0.0. DO NOT EDIT.

package identitymanagermocks

import (
	context "context"

	fftypes "github.com/hyperledger-labs/firefly/pkg/fftypes"

	mock "github.com/stretchr/testify/mock"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// ResolveInputIdentity provides a mock function with given fields: ctx, _a1
func (_m *Manager) ResolveInputIdentity(ctx context.Context, _a1 *fftypes.Identity) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.Identity) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
