// Code generated by mockery v1.0.0. DO NOT EDIT.

package metricsmocks

import (
	fftypes "github.com/hyperledger/firefly/pkg/fftypes"

	mock "github.com/stretchr/testify/mock"

	time "time"

	tokens "github.com/hyperledger/firefly/pkg/tokens"
)

// Manager is an autogenerated mock type for the Manager type
type Manager struct {
	mock.Mock
}

// AddTime provides a mock function with given fields: id
func (_m *Manager) AddTime(id string) {
	_m.Called(id)
}

// DeleteTime provides a mock function with given fields: id
func (_m *Manager) DeleteTime(id string) {
	_m.Called(id)
}

// GetTime provides a mock function with given fields: id
func (_m *Manager) GetTime(id string) time.Time {
	ret := _m.Called(id)

	var r0 time.Time
	if rf, ok := ret.Get(0).(func(string) time.Time); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MessageConfirmed provides a mock function with given fields: msg, eventType
func (_m *Manager) MessageConfirmed(msg *fftypes.Message, eventType fftypes.FFEnum) {
	_m.Called(msg, eventType)
}

// MessageSubmitted provides a mock function with given fields: in
func (_m *Manager) MessageSubmitted(in *fftypes.MessageInOut) {
	_m.Called(in)
}

// Start provides a mock function with given fields:
func (_m *Manager) Start() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransferConfirmed provides a mock function with given fields: transfer
func (_m *Manager) TransferConfirmed(transfer *tokens.TokenTransfer) {
	_m.Called(transfer)
}

// TransferSubmitted provides a mock function with given fields: transfer
func (_m *Manager) TransferSubmitted(transfer *fftypes.TokenTransferInput) {
	_m.Called(transfer)
}
