// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package persistence

import (
	context "context"

	fftypes "github.com/kaleido-io/firefly/internal/fftypes"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPlugin is an autogenerated mock type for the Plugin type
type MockPlugin struct {
	mock.Mock
}

// ConfigInterface provides a mock function with given fields:
func (_m *MockPlugin) ConfigInterface() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// GetBatchById provides a mock function with given fields: ctx, id
func (_m *MockPlugin) GetBatchById(ctx context.Context, id *uuid.UUID) (*fftypes.Batch, error) {
	ret := _m.Called(ctx, id)

	var r0 *fftypes.Batch
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) *fftypes.Batch); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fftypes.Batch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBatches provides a mock function with given fields: ctx, skip, limit, filter
func (_m *MockPlugin) GetBatches(ctx context.Context, skip uint64, limit uint64, filter *BatchFilter) ([]*fftypes.Batch, error) {
	ret := _m.Called(ctx, skip, limit, filter)

	var r0 []*fftypes.Batch
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, *BatchFilter) []*fftypes.Batch); ok {
		r0 = rf(ctx, skip, limit, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fftypes.Batch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64, *BatchFilter) error); ok {
		r1 = rf(ctx, skip, limit, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDataById provides a mock function with given fields: ctx, id
func (_m *MockPlugin) GetDataById(ctx context.Context, id *uuid.UUID) (*fftypes.Data, error) {
	ret := _m.Called(ctx, id)

	var r0 *fftypes.Data
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) *fftypes.Data); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fftypes.Data)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessageById provides a mock function with given fields: ctx, id
func (_m *MockPlugin) GetMessageById(ctx context.Context, id *uuid.UUID) (*fftypes.MessageRefsOnly, error) {
	ret := _m.Called(ctx, id)

	var r0 *fftypes.MessageRefsOnly
	if rf, ok := ret.Get(0).(func(context.Context, *uuid.UUID) *fftypes.MessageRefsOnly); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*fftypes.MessageRefsOnly)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMessages provides a mock function with given fields: ctx, skip, limit, filter
func (_m *MockPlugin) GetMessages(ctx context.Context, skip uint64, limit uint64, filter *MessageFilter) ([]*fftypes.MessageRefsOnly, error) {
	ret := _m.Called(ctx, skip, limit, filter)

	var r0 []*fftypes.MessageRefsOnly
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64, *MessageFilter) []*fftypes.MessageRefsOnly); ok {
		r0 = rf(ctx, skip, limit, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*fftypes.MessageRefsOnly)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64, *MessageFilter) error); ok {
		r1 = rf(ctx, skip, limit, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: ctx, config, events
func (_m *MockPlugin) Init(ctx context.Context, config interface{}, events Events) (*Capabilities, error) {
	ret := _m.Called(ctx, config, events)

	var r0 *Capabilities
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, Events) *Capabilities); ok {
		r0 = rf(ctx, config, events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Capabilities)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, interface{}, Events) error); ok {
		r1 = rf(ctx, config, events)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertBatch provides a mock function with given fields: ctx, data
func (_m *MockPlugin) UpsertBatch(ctx context.Context, data *fftypes.Batch) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.Batch) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertData provides a mock function with given fields: ctx, data
func (_m *MockPlugin) UpsertData(ctx context.Context, data *fftypes.Data) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.Data) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpsertMessage provides a mock function with given fields: ctx, message
func (_m *MockPlugin) UpsertMessage(ctx context.Context, message *fftypes.MessageRefsOnly) error {
	ret := _m.Called(ctx, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *fftypes.MessageRefsOnly) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
