// Code generated by mockery v1.0.0. DO NOT EDIT.

package coremocks

import (
	core "github.com/hyperledger/firefly/pkg/core"
	mock "github.com/stretchr/testify/mock"
)

// OperationCallbacks is an autogenerated mock type for the OperationCallbacks type
type OperationCallbacks struct {
	mock.Mock
}

// OperationUpdate provides a mock function with given fields: plugin, update
func (_m *OperationCallbacks) OperationUpdate(plugin core.Named, update *core.OperationUpdate) {
	_m.Called(plugin, update)
}
