// Code generated by mockery v1.0.0. DO NOT EDIT.

package dataexchangemocks

import (
	dataexchange "github.com/hyperledger/firefly/pkg/dataexchange"
	mock "github.com/stretchr/testify/mock"
)

// Callbacks is an autogenerated mock type for the Callbacks type
type Callbacks struct {
	mock.Mock
}

// DXEvent provides a mock function with given fields: plugin, event
func (_m *Callbacks) DXEvent(plugin dataexchange.Plugin, event dataexchange.DXEvent) {
	_m.Called(plugin, event)
}
