// Code generated by mockery v1.0.0. DO NOT EDIT.

package dataexchangemocks

import (
	fftypes "github.com/hyperledger-labs/firefly/pkg/fftypes"
	mock "github.com/stretchr/testify/mock"
)

// Callbacks is an autogenerated mock type for the Callbacks type
type Callbacks struct {
	mock.Mock
}

// BLOBReceived provides a mock function with given fields: peerID, hash, payloadRef
func (_m *Callbacks) BLOBReceived(peerID string, hash *fftypes.Bytes32, payloadRef string) {
	_m.Called(peerID, hash, payloadRef)
}

// MessageReceived provides a mock function with given fields: peerID, data
func (_m *Callbacks) MessageReceived(peerID string, data []byte) {
	_m.Called(peerID, data)
}

// TransferResult provides a mock function with given fields: trackingID, status, info, additionalInfo
func (_m *Callbacks) TransferResult(trackingID string, status fftypes.OpStatus, info string, additionalInfo fftypes.JSONObject) {
	_m.Called(trackingID, status, info, additionalInfo)
}
