// Code generated by mockery v2.14.1. DO NOT EDIT.

package apiservermocks

import (
	context "context"

	namespace "github.com/hyperledger/firefly/internal/namespace"
	mock "github.com/stretchr/testify/mock"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

// Serve provides a mock function with given fields: ctx, mgr
func (_m *Server) Serve(ctx context.Context, mgr namespace.Manager) error {
	ret := _m.Called(ctx, mgr)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, namespace.Manager) error); ok {
		r0 = rf(ctx, mgr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServer(t mockConstructorTestingTNewServer) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
