# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 3.3"

gem "jekyll-theme-cayman", "~> 0.1.1"

gem "kramdown-parser-gfm", "~> 1.1"

gem "just-the-docs", "~> 0.3.3"
