name: Docker

on:
  release:
    types: [published, prereleased]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t ghcr.io/hyperledger/firefly:${GITHUB_REF##*/} .
      
      - name: Tag release
        if: github.event.action == 'published'
        run: docker tag ghcr.io/hyperledger/firefly:${GITHUB_REF##*/} ghcr.io/hyperledger/firefly:latest
      
      - name: Push docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/hyperledger/firefly:${GITHUB_REF##*/}
      
      - name: Push latest tag
        if: github.event.action == 'published'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/hyperledger/firefly:latest