apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firefly.fullname" . }}-config
  labels:
    {{- include "firefly.coreLabels" . | nindent 4 }}
stringData:
  {{- if and .Values.config.postgresUrl .Values.config.postgresMigrationJob -}}
  psql_url: {{ tpl .Values.config.postgresUrl . }}
  {{- end }}
  firefly.core: |
    {{- if .Values.config.templateOverride }}
    {{- toYaml (tpl .Values.config.templateOverride .) | nindent 4 }}
    {{- else }}
    {{- include "firefly.coreConfig" . | nindent 4 }}
    {{- end }}
